// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCS_ztkvwMxXmlcEj-yPmvJb84W6XDVQ',
    appId: '1:53567551706:web:48b52136f328b68e70cde3',
    messagingSenderId: '53567551706',
    projectId: 'memorise-9e7c6',
    authDomain: 'memorise-9e7c6.firebaseapp.com',
    storageBucket: 'memorise-9e7c6.firebasestorage.app',
    measurementId: 'G-82Y74QCS4B',
    databaseURL:
    'https://memorise-9e7c6-default-rtdb.asia-southeast1.firebasedatabase.app', // Pastikan URL ini benar
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6P2nRT3F1ZH8wsCaWv6S6_u_B1moFhu0',
    appId: '1:53567551706:android:25396a00cff580c970cde3',
    messagingSenderId: '53567551706',
    projectId: 'memorise-9e7c6',
    storageBucket: 'memorise-9e7c6.firebasestorage.app',
    databaseURL:
        'https://memorise-9e7c6-default-rtdb.asia-southeast1.firebasedatabase.app', // Pastikan URL ini benar
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2oO9Q8bmDzoNFxYFhk6zjI_7W9FCLMqw',
    appId: '1:53567551706:ios:37116f832f2be97670cde3',
    messagingSenderId: '53567551706',
    projectId: 'memorise-9e7c6',
    storageBucket: 'memorise-9e7c6.firebasestorage.app',
    iosBundleId: 'com.example.memoriesrecorder',
    databaseURL:
    'https://memorise-9e7c6-default-rtdb.asia-southeast1.firebasedatabase.app', // Pastikan URL ini benar
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2oO9Q8bmDzoNFxYFhk6zjI_7W9FCLMqw',
    appId: '1:53567551706:ios:37116f832f2be97670cde3',
    messagingSenderId: '53567551706',
    projectId: 'memorise-9e7c6',
    storageBucket: 'memorise-9e7c6.firebasestorage.app',
    iosBundleId: 'com.example.memoriesrecorder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALCS_ztkvwMxXmlcEj-yPmvJb84W6XDVQ',
    appId: '1:53567551706:web:34c473c5bb942a9070cde3',
    messagingSenderId: '53567551706',
    projectId: 'memorise-9e7c6',
    authDomain: 'memorise-9e7c6.firebaseapp.com',
    storageBucket: 'memorise-9e7c6.firebasestorage.app',
    measurementId: 'G-2WTHT6Z4DN',
  );
}
